version: "3.8"

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
        - /app/node_modules
    env_file:
      - .env
    environment:
      NODE_ENV: development
    command: npm run dev
